import matplotlib.pyplot as pplot
import numpy as np
import os

# USEFUL FUNCTIONS
def ReadFile(name):
    # Using numpy to read the results generated by acompanying c++ file
    return np.genfromtxt(name, delimiter=',')

# PLOT RESULTS
data = ReadFile(os.getcwd() + "/results.dat")
Figure = pplot.figure(figsize=[10,4])
pplot.plot(data[:,0], data[:,1])
pplot.ylim(bottom=0)
pplot.xlabel("Time [s]")
pplot.ylabel("Particle KE [k]")
pplot.title("Particle Kinetic Energy (L = 25cm, l=5cm, $0.5\omega$=$\omega_I$)")
pplot.show()