import matplotlib.pyplot as pplot
import numpy as np
import os

# USEFUL FUNCTIONS
def ReadFile(name):
    # Using numpy to read the results generated by acompanying c++ file
    return np.genfromtxt(name, delimiter=',')

# PLOT RESULTS
data = ReadFile(os.getcwd() + "/results.dat")
walk = ReadFile(os.getcwd() + "/walk.dat")


Fig, axs = pplot.subplots(2)
Fig.set_size_inches((10,7))
Fig.suptitle("Standing Wave, Switched at Const Freq, $K_i = 0.001$, $x_i = 0m$, $A_0 = 0.0005K$, $k=773.291m^{-1}$")

axs[0].plot(data[:,0], data[:,1])
axs[0].set(ylabel="Particle KE [k]")
axs[0].set_title("Particle Kinetic Energy")

axs[1].plot(walk[:,0], walk[:,1])
axs[1].set(xlabel="Time [s]", ylabel="Particle Momentum [kgm$^{-1}$]")
axs[1].set_title("Particle Momentum")

pplot.show()